compiler: gcc

language: c

jobs:
  include:
    - name: "Build and Test - Stage 1"
    env: STAGE=stage1
    - name: "Build and Test - Stage 2"
    env: STAGE=stage2
    
script: cd projects/project_2/$STAGE && make && make test
    
