#!/bin/bash

if [ "$1" != "" ]; then
	echo " Compiling and executing $1 ..."

	rm $1 -f
	rm *.o -f
	echo
	cc -Wall -o $1 "$1.c"

	if [ "$?" != 0 ]; then
		echo "COMPILATION_ERROR"
	else
		./$1
	fi 
else
	echo "type a filename to compile and execute" 
fi
