#!/bin/bash

# flag -l is always set
echo "Compiling ..."
make
echo "Compiled!"


echo "Testing simple du ..."

# On TestDir
# flags -L -a -b (read bytes from all files)
echo "TEST1 | -a -b -L on TestDir"
(./simpledu -l ../TestDir/ -L -a -b || echo $?) | sort -k2 > ../teste_simpledu.txt
(du -l ../TestDir/ -L -a -b || echo $?) | sort -k2 > ../teste_du.txt

DIFF=$(diff -q ../teste_simpledu.txt ../teste_du.txt)

if [ "$DIFF" ]
then
	echo "FAIL"
else
	echo "OK"
fi


# On current folder
# flags -L -a -b (read bytes from all files)
echo "TEST2 | -a -b -L on Root"
(./simpledu -l . -L -a -b || echo $?) | sort -k2 > ../teste_simpledu.txt
(du -l . -L -a -b || echo $?) | sort -k2 > ../teste_du.txt

DIFF=$(diff -q ../teste_simpledu.txt ../teste_du.txt)
if [ "$DIFF" ]
then
	echo "FAIL"
else
	echo "OK"
fi

# On current folder/
# flags -L -a -b (read bytes from all files)
echo "TEST3 | -a -b -L on Root/"
(./simpledu -l ./ -L -a -b || echo $?) | sort -k2 > ../teste_simpledu.txt
(du -l ./ -L -a -b || echo $?) | sort -k2 > ../teste_du.txt

DIFF=$(diff -q ../teste_simpledu.txt ../teste_du.txt)
if [ "$DIFF" ]
then
	echo "FAIL"
else
	echo "OK"
fi

# On Downloads folder
# flags -L -a -b (read bytes from all files)
echo "TEST4 | -a -b -L on Downloads"
(./simpledu -l /mnt/c/Users/skidr/Downloads/ -L -a -b || echo $?) | sort -k2 > ../teste_simpledu.txt
(du -l /mnt/c/Users/skidr/Downloads/ -L -a -b || echo $?) | sort -k2 > ../teste_du.txt

DIFF=$(diff -q ../teste_simpledu.txt ../teste_du.txt)
if [ "$DIFF" ]
then
	echo "FAIL"
else
	echo "OK"
fi


echo "TEST5 | -a -b on TestDir"
(./simpledu -l ../TestDir -a -b || echo $?) | sort -k2 > ../teste_simpledu.txt
(du -l ../TestDir -a -b || echo $?) | sort -k2 > ../teste_du.txt

DIFF=$(diff -q ../teste_simpledu.txt ../teste_du.txt)
if [ "$DIFF" ]
then
	echo "FAIL"
else
  echo "OK"
fi


echo "TEST6 | -a -b on TestDir/"
(./simpledu -l ../TestDir/ -a -b || echo $?) | sort -k2 > ../teste_simpledu.txt
(du -l ../TestDir/ -a -b || echo $?) | sort -k2 > ../teste_du.txt

DIFF=$(diff -q ../teste_simpledu.txt ../teste_du.txt)
if [ "$DIFF" ]
then
	echo "FAIL"
else
  echo "OK"
fi

# clean
rm ../*teste* > /dev/null
make clean
