name: Project 2 - WC Server/Client - Stage 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd projects/project_2/stage1/ && make
    - name: make test
      run: cd projects/project_2/stage1/ && make test
