name: Project 2 - WC Server/Client - Stage 2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd projects/project_2/stage2/ && make
    - name: make test
      run: cd projects/project_2/stage2/ && make test
  
  example:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: cd projects/project_2/stage2/ && make
      - name: server time to 2s and client to 3s | nplaces to 4 and pthreads to 10
        run: cd projects/project_2/stage2/ && (./Q2 -t 2 -n 4 -l 10 fifo.server & ./U2 -t 3 fifo.server)
